(function(){
  'use strict';
  var _data = [
  {
    "login": "owencraig",
    "id": 1683690,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683690?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/owencraig",
    "html_url": "https://github.com/owencraig",
    "followers_url": "https://api.github.com/users/owencraig/followers",
    "following_url": "https://api.github.com/users/owencraig/following{/other_user}",
    "gists_url": "https://api.github.com/users/owencraig/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/owencraig/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/owencraig/subscriptions",
    "organizations_url": "https://api.github.com/users/owencraig/orgs",
    "repos_url": "https://api.github.com/users/owencraig/repos",
    "events_url": "https://api.github.com/users/owencraig/events{/privacy}",
    "received_events_url": "https://api.github.com/users/owencraig/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "HankG",
    "id": 1683691,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683691?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/HankG",
    "html_url": "https://github.com/HankG",
    "followers_url": "https://api.github.com/users/HankG/followers",
    "following_url": "https://api.github.com/users/HankG/following{/other_user}",
    "gists_url": "https://api.github.com/users/HankG/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/HankG/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/HankG/subscriptions",
    "organizations_url": "https://api.github.com/users/HankG/orgs",
    "repos_url": "https://api.github.com/users/HankG/repos",
    "events_url": "https://api.github.com/users/HankG/events{/privacy}",
    "received_events_url": "https://api.github.com/users/HankG/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "bananapie62",
    "id": 1683692,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683692?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/bananapie62",
    "html_url": "https://github.com/bananapie62",
    "followers_url": "https://api.github.com/users/bananapie62/followers",
    "following_url": "https://api.github.com/users/bananapie62/following{/other_user}",
    "gists_url": "https://api.github.com/users/bananapie62/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/bananapie62/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/bananapie62/subscriptions",
    "organizations_url": "https://api.github.com/users/bananapie62/orgs",
    "repos_url": "https://api.github.com/users/bananapie62/repos",
    "events_url": "https://api.github.com/users/bananapie62/events{/privacy}",
    "received_events_url": "https://api.github.com/users/bananapie62/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Metaridley17",
    "id": 1683693,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683693?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Metaridley17",
    "html_url": "https://github.com/Metaridley17",
    "followers_url": "https://api.github.com/users/Metaridley17/followers",
    "following_url": "https://api.github.com/users/Metaridley17/following{/other_user}",
    "gists_url": "https://api.github.com/users/Metaridley17/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Metaridley17/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Metaridley17/subscriptions",
    "organizations_url": "https://api.github.com/users/Metaridley17/orgs",
    "repos_url": "https://api.github.com/users/Metaridley17/repos",
    "events_url": "https://api.github.com/users/Metaridley17/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Metaridley17/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "michaelgriffith",
    "id": 1683694,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683694?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/michaelgriffith",
    "html_url": "https://github.com/michaelgriffith",
    "followers_url": "https://api.github.com/users/michaelgriffith/followers",
    "following_url": "https://api.github.com/users/michaelgriffith/following{/other_user}",
    "gists_url": "https://api.github.com/users/michaelgriffith/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/michaelgriffith/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/michaelgriffith/subscriptions",
    "organizations_url": "https://api.github.com/users/michaelgriffith/orgs",
    "repos_url": "https://api.github.com/users/michaelgriffith/repos",
    "events_url": "https://api.github.com/users/michaelgriffith/events{/privacy}",
    "received_events_url": "https://api.github.com/users/michaelgriffith/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "dreign",
    "id": 1683695,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683695?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dreign",
    "html_url": "https://github.com/dreign",
    "followers_url": "https://api.github.com/users/dreign/followers",
    "following_url": "https://api.github.com/users/dreign/following{/other_user}",
    "gists_url": "https://api.github.com/users/dreign/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dreign/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dreign/subscriptions",
    "organizations_url": "https://api.github.com/users/dreign/orgs",
    "repos_url": "https://api.github.com/users/dreign/repos",
    "events_url": "https://api.github.com/users/dreign/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dreign/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "lawrenceyap",
    "id": 1683696,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683696?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/lawrenceyap",
    "html_url": "https://github.com/lawrenceyap",
    "followers_url": "https://api.github.com/users/lawrenceyap/followers",
    "following_url": "https://api.github.com/users/lawrenceyap/following{/other_user}",
    "gists_url": "https://api.github.com/users/lawrenceyap/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/lawrenceyap/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/lawrenceyap/subscriptions",
    "organizations_url": "https://api.github.com/users/lawrenceyap/orgs",
    "repos_url": "https://api.github.com/users/lawrenceyap/repos",
    "events_url": "https://api.github.com/users/lawrenceyap/events{/privacy}",
    "received_events_url": "https://api.github.com/users/lawrenceyap/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "rajeevaruba",
    "id": 1683697,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683697?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rajeevaruba",
    "html_url": "https://github.com/rajeevaruba",
    "followers_url": "https://api.github.com/users/rajeevaruba/followers",
    "following_url": "https://api.github.com/users/rajeevaruba/following{/other_user}",
    "gists_url": "https://api.github.com/users/rajeevaruba/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rajeevaruba/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rajeevaruba/subscriptions",
    "organizations_url": "https://api.github.com/users/rajeevaruba/orgs",
    "repos_url": "https://api.github.com/users/rajeevaruba/repos",
    "events_url": "https://api.github.com/users/rajeevaruba/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rajeevaruba/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "vb7",
    "id": 1683698,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683698?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/vb7",
    "html_url": "https://github.com/vb7",
    "followers_url": "https://api.github.com/users/vb7/followers",
    "following_url": "https://api.github.com/users/vb7/following{/other_user}",
    "gists_url": "https://api.github.com/users/vb7/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/vb7/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/vb7/subscriptions",
    "organizations_url": "https://api.github.com/users/vb7/orgs",
    "repos_url": "https://api.github.com/users/vb7/repos",
    "events_url": "https://api.github.com/users/vb7/events{/privacy}",
    "received_events_url": "https://api.github.com/users/vb7/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Silentrob567",
    "id": 1683699,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683699?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Silentrob567",
    "html_url": "https://github.com/Silentrob567",
    "followers_url": "https://api.github.com/users/Silentrob567/followers",
    "following_url": "https://api.github.com/users/Silentrob567/following{/other_user}",
    "gists_url": "https://api.github.com/users/Silentrob567/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Silentrob567/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Silentrob567/subscriptions",
    "organizations_url": "https://api.github.com/users/Silentrob567/orgs",
    "repos_url": "https://api.github.com/users/Silentrob567/repos",
    "events_url": "https://api.github.com/users/Silentrob567/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Silentrob567/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "i-fail",
    "id": 1683700,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683700?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/i-fail",
    "html_url": "https://github.com/i-fail",
    "followers_url": "https://api.github.com/users/i-fail/followers",
    "following_url": "https://api.github.com/users/i-fail/following{/other_user}",
    "gists_url": "https://api.github.com/users/i-fail/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/i-fail/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/i-fail/subscriptions",
    "organizations_url": "https://api.github.com/users/i-fail/orgs",
    "repos_url": "https://api.github.com/users/i-fail/repos",
    "events_url": "https://api.github.com/users/i-fail/events{/privacy}",
    "received_events_url": "https://api.github.com/users/i-fail/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "JW-Leon",
    "id": 1683701,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683701?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/JW-Leon",
    "html_url": "https://github.com/JW-Leon",
    "followers_url": "https://api.github.com/users/JW-Leon/followers",
    "following_url": "https://api.github.com/users/JW-Leon/following{/other_user}",
    "gists_url": "https://api.github.com/users/JW-Leon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/JW-Leon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/JW-Leon/subscriptions",
    "organizations_url": "https://api.github.com/users/JW-Leon/orgs",
    "repos_url": "https://api.github.com/users/JW-Leon/repos",
    "events_url": "https://api.github.com/users/JW-Leon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/JW-Leon/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "fromjapanwithlove",
    "id": 1683702,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683702?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/fromjapanwithlove",
    "html_url": "https://github.com/fromjapanwithlove",
    "followers_url": "https://api.github.com/users/fromjapanwithlove/followers",
    "following_url": "https://api.github.com/users/fromjapanwithlove/following{/other_user}",
    "gists_url": "https://api.github.com/users/fromjapanwithlove/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/fromjapanwithlove/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/fromjapanwithlove/subscriptions",
    "organizations_url": "https://api.github.com/users/fromjapanwithlove/orgs",
    "repos_url": "https://api.github.com/users/fromjapanwithlove/repos",
    "events_url": "https://api.github.com/users/fromjapanwithlove/events{/privacy}",
    "received_events_url": "https://api.github.com/users/fromjapanwithlove/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "shillman1",
    "id": 1683703,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683703?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/shillman1",
    "html_url": "https://github.com/shillman1",
    "followers_url": "https://api.github.com/users/shillman1/followers",
    "following_url": "https://api.github.com/users/shillman1/following{/other_user}",
    "gists_url": "https://api.github.com/users/shillman1/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/shillman1/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/shillman1/subscriptions",
    "organizations_url": "https://api.github.com/users/shillman1/orgs",
    "repos_url": "https://api.github.com/users/shillman1/repos",
    "events_url": "https://api.github.com/users/shillman1/events{/privacy}",
    "received_events_url": "https://api.github.com/users/shillman1/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "winsx",
    "id": 1683704,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683704?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/winsx",
    "html_url": "https://github.com/winsx",
    "followers_url": "https://api.github.com/users/winsx/followers",
    "following_url": "https://api.github.com/users/winsx/following{/other_user}",
    "gists_url": "https://api.github.com/users/winsx/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/winsx/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/winsx/subscriptions",
    "organizations_url": "https://api.github.com/users/winsx/orgs",
    "repos_url": "https://api.github.com/users/winsx/repos",
    "events_url": "https://api.github.com/users/winsx/events{/privacy}",
    "received_events_url": "https://api.github.com/users/winsx/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "stembro",
    "id": 1683705,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683705?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/stembro",
    "html_url": "https://github.com/stembro",
    "followers_url": "https://api.github.com/users/stembro/followers",
    "following_url": "https://api.github.com/users/stembro/following{/other_user}",
    "gists_url": "https://api.github.com/users/stembro/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/stembro/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/stembro/subscriptions",
    "organizations_url": "https://api.github.com/users/stembro/orgs",
    "repos_url": "https://api.github.com/users/stembro/repos",
    "events_url": "https://api.github.com/users/stembro/events{/privacy}",
    "received_events_url": "https://api.github.com/users/stembro/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Radar11x",
    "id": 1683706,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683706?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Radar11x",
    "html_url": "https://github.com/Radar11x",
    "followers_url": "https://api.github.com/users/Radar11x/followers",
    "following_url": "https://api.github.com/users/Radar11x/following{/other_user}",
    "gists_url": "https://api.github.com/users/Radar11x/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Radar11x/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Radar11x/subscriptions",
    "organizations_url": "https://api.github.com/users/Radar11x/orgs",
    "repos_url": "https://api.github.com/users/Radar11x/repos",
    "events_url": "https://api.github.com/users/Radar11x/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Radar11x/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "forecast",
    "id": 1683707,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683707?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/forecast",
    "html_url": "https://github.com/forecast",
    "followers_url": "https://api.github.com/users/forecast/followers",
    "following_url": "https://api.github.com/users/forecast/following{/other_user}",
    "gists_url": "https://api.github.com/users/forecast/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/forecast/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/forecast/subscriptions",
    "organizations_url": "https://api.github.com/users/forecast/orgs",
    "repos_url": "https://api.github.com/users/forecast/repos",
    "events_url": "https://api.github.com/users/forecast/events{/privacy}",
    "received_events_url": "https://api.github.com/users/forecast/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "sunhmt",
    "id": 1683708,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683708?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sunhmt",
    "html_url": "https://github.com/sunhmt",
    "followers_url": "https://api.github.com/users/sunhmt/followers",
    "following_url": "https://api.github.com/users/sunhmt/following{/other_user}",
    "gists_url": "https://api.github.com/users/sunhmt/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sunhmt/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sunhmt/subscriptions",
    "organizations_url": "https://api.github.com/users/sunhmt/orgs",
    "repos_url": "https://api.github.com/users/sunhmt/repos",
    "events_url": "https://api.github.com/users/sunhmt/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sunhmt/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "pietpuk",
    "id": 1683709,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683709?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/pietpuk",
    "html_url": "https://github.com/pietpuk",
    "followers_url": "https://api.github.com/users/pietpuk/followers",
    "following_url": "https://api.github.com/users/pietpuk/following{/other_user}",
    "gists_url": "https://api.github.com/users/pietpuk/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/pietpuk/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/pietpuk/subscriptions",
    "organizations_url": "https://api.github.com/users/pietpuk/orgs",
    "repos_url": "https://api.github.com/users/pietpuk/repos",
    "events_url": "https://api.github.com/users/pietpuk/events{/privacy}",
    "received_events_url": "https://api.github.com/users/pietpuk/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "PdeQuadros",
    "id": 1683710,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683710?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/PdeQuadros",
    "html_url": "https://github.com/PdeQuadros",
    "followers_url": "https://api.github.com/users/PdeQuadros/followers",
    "following_url": "https://api.github.com/users/PdeQuadros/following{/other_user}",
    "gists_url": "https://api.github.com/users/PdeQuadros/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/PdeQuadros/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/PdeQuadros/subscriptions",
    "organizations_url": "https://api.github.com/users/PdeQuadros/orgs",
    "repos_url": "https://api.github.com/users/PdeQuadros/repos",
    "events_url": "https://api.github.com/users/PdeQuadros/events{/privacy}",
    "received_events_url": "https://api.github.com/users/PdeQuadros/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "liam004",
    "id": 1683711,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683711?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/liam004",
    "html_url": "https://github.com/liam004",
    "followers_url": "https://api.github.com/users/liam004/followers",
    "following_url": "https://api.github.com/users/liam004/following{/other_user}",
    "gists_url": "https://api.github.com/users/liam004/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/liam004/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/liam004/subscriptions",
    "organizations_url": "https://api.github.com/users/liam004/orgs",
    "repos_url": "https://api.github.com/users/liam004/repos",
    "events_url": "https://api.github.com/users/liam004/events{/privacy}",
    "received_events_url": "https://api.github.com/users/liam004/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Calidus",
    "id": 1683712,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683712?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Calidus",
    "html_url": "https://github.com/Calidus",
    "followers_url": "https://api.github.com/users/Calidus/followers",
    "following_url": "https://api.github.com/users/Calidus/following{/other_user}",
    "gists_url": "https://api.github.com/users/Calidus/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Calidus/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Calidus/subscriptions",
    "organizations_url": "https://api.github.com/users/Calidus/orgs",
    "repos_url": "https://api.github.com/users/Calidus/repos",
    "events_url": "https://api.github.com/users/Calidus/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Calidus/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "mxz297",
    "id": 1683713,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683713?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mxz297",
    "html_url": "https://github.com/mxz297",
    "followers_url": "https://api.github.com/users/mxz297/followers",
    "following_url": "https://api.github.com/users/mxz297/following{/other_user}",
    "gists_url": "https://api.github.com/users/mxz297/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mxz297/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mxz297/subscriptions",
    "organizations_url": "https://api.github.com/users/mxz297/orgs",
    "repos_url": "https://api.github.com/users/mxz297/repos",
    "events_url": "https://api.github.com/users/mxz297/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mxz297/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "naysayer",
    "id": 1683714,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683714?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/naysayer",
    "html_url": "https://github.com/naysayer",
    "followers_url": "https://api.github.com/users/naysayer/followers",
    "following_url": "https://api.github.com/users/naysayer/following{/other_user}",
    "gists_url": "https://api.github.com/users/naysayer/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/naysayer/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/naysayer/subscriptions",
    "organizations_url": "https://api.github.com/users/naysayer/orgs",
    "repos_url": "https://api.github.com/users/naysayer/repos",
    "events_url": "https://api.github.com/users/naysayer/events{/privacy}",
    "received_events_url": "https://api.github.com/users/naysayer/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "JennyGriffith",
    "id": 1683715,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683715?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/JennyGriffith",
    "html_url": "https://github.com/JennyGriffith",
    "followers_url": "https://api.github.com/users/JennyGriffith/followers",
    "following_url": "https://api.github.com/users/JennyGriffith/following{/other_user}",
    "gists_url": "https://api.github.com/users/JennyGriffith/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/JennyGriffith/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/JennyGriffith/subscriptions",
    "organizations_url": "https://api.github.com/users/JennyGriffith/orgs",
    "repos_url": "https://api.github.com/users/JennyGriffith/repos",
    "events_url": "https://api.github.com/users/JennyGriffith/events{/privacy}",
    "received_events_url": "https://api.github.com/users/JennyGriffith/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "myberlina",
    "id": 1683716,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683716?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/myberlina",
    "html_url": "https://github.com/myberlina",
    "followers_url": "https://api.github.com/users/myberlina/followers",
    "following_url": "https://api.github.com/users/myberlina/following{/other_user}",
    "gists_url": "https://api.github.com/users/myberlina/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/myberlina/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/myberlina/subscriptions",
    "organizations_url": "https://api.github.com/users/myberlina/orgs",
    "repos_url": "https://api.github.com/users/myberlina/repos",
    "events_url": "https://api.github.com/users/myberlina/events{/privacy}",
    "received_events_url": "https://api.github.com/users/myberlina/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "zaltin",
    "id": 1683717,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683717?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/zaltin",
    "html_url": "https://github.com/zaltin",
    "followers_url": "https://api.github.com/users/zaltin/followers",
    "following_url": "https://api.github.com/users/zaltin/following{/other_user}",
    "gists_url": "https://api.github.com/users/zaltin/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/zaltin/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/zaltin/subscriptions",
    "organizations_url": "https://api.github.com/users/zaltin/orgs",
    "repos_url": "https://api.github.com/users/zaltin/repos",
    "events_url": "https://api.github.com/users/zaltin/events{/privacy}",
    "received_events_url": "https://api.github.com/users/zaltin/received_events",
    "type": "Organization",
    "site_admin": false
  },
  {
    "login": "ryanrahn",
    "id": 1683719,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683719?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ryanrahn",
    "html_url": "https://github.com/ryanrahn",
    "followers_url": "https://api.github.com/users/ryanrahn/followers",
    "following_url": "https://api.github.com/users/ryanrahn/following{/other_user}",
    "gists_url": "https://api.github.com/users/ryanrahn/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ryanrahn/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ryanrahn/subscriptions",
    "organizations_url": "https://api.github.com/users/ryanrahn/orgs",
    "repos_url": "https://api.github.com/users/ryanrahn/repos",
    "events_url": "https://api.github.com/users/ryanrahn/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ryanrahn/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "killmeifyou9",
    "id": 1683720,
    "avatar_url": "https://avatars.githubusercontent.com/u/1683720?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/killmeifyou9",
    "html_url": "https://github.com/killmeifyou9",
    "followers_url": "https://api.github.com/users/killmeifyou9/followers",
    "following_url": "https://api.github.com/users/killmeifyou9/following{/other_user}",
    "gists_url": "https://api.github.com/users/killmeifyou9/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/killmeifyou9/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/killmeifyou9/subscriptions",
    "organizations_url": "https://api.github.com/users/killmeifyou9/orgs",
    "repos_url": "https://api.github.com/users/killmeifyou9/repos",
    "events_url": "https://api.github.com/users/killmeifyou9/events{/privacy}",
    "received_events_url": "https://api.github.com/users/killmeifyou9/received_events",
    "type": "User",
    "site_admin": false
  }
];
  angular.module('RouterApplication').factory('githubDataService', function($http, $timeout){
    return {
      getUsersHttp: getUsersHttp,
      getUsers: getUsers
    };

    function getUsers(){
      return $timeout(getUsersStatic, 1000);
    }

    function getUsersStatic(){
      return _data;
    }

    function getUsersHttp(since){
      return $http({
        method: 'GET',
        url: 'https://api.github.com/users',
        params: {
          since: since
        }
      }).then(function(response){
        return response.data;
      });
    }
  });
})();